# Generated by Django 3.2.6 on 2022-10-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='jefe_inmediato',
            field=models.CharField(max_length=50),
        ),
    ]
