# Generated by Django 3.2.6 on 2022-10-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_colaborador_jefe_inmediato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='sede',
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipio_sede', to='home.municipio'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipio_destino', to='home.municipio'),
        ),
    ]
