# Generated by Django 3.2.6 on 2022-11-15 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_regional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ruta',
            new_name='TablaViaticos',
        ),
        migrations.CreateModel(
            name='Viatico',
            fields=[
                ('tablaviaticos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.tablaviaticos')),
                ('num_dias', models.IntegerField()),
                ('esPernoctado', models.BooleanField(default=False)),
                ('rutaAprobada', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.actividad')),
            ],
            bases=('home.tablaviaticos',),
        ),
        migrations.CreateModel(
            name='GastoAdicional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.actividad')),
            ],
        ),
    ]
