# Generated by Django 3.2.6 on 2022-11-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221115_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaViatico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('dias_viaje', models.IntegerField()),
                ('pernoctar', models.BooleanField()),
                ('transporte', models.FloatField()),
                ('viatico', models.FloatField()),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='concepto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='gastoadicional',
            old_name='Actividad',
            new_name='actividad',
        ),
        migrations.RenameField(
            model_name='solicitudrecurso',
            old_name='valorTotal',
            new_name='valor_total',
        ),
        migrations.AddField(
            model_name='actividad',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.municipio'),
        ),
        migrations.AddField(
            model_name='gastoadicional',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gastoadicional',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solicitudrecurso',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.regional'),
        ),
        migrations.DeleteModel(
            name='Viatico',
        ),
        migrations.AddField(
            model_name='rutaviatico',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.actividad'),
        ),
        migrations.AddField(
            model_name='rutaviatico',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punto_final', to='home.municipio'),
        ),
        migrations.AddField(
            model_name='rutaviatico',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punto_origen', to='home.municipio'),
        ),
    ]
