# Generated by Django 3.2.6 on 2022-11-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221125_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudrecurso',
            old_name='Observaciones',
            new_name='observaciones',
        ),
    ]
