# Generated by Django 3.2.6 on 2022-11-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221128_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoadicional',
            name='minicipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.municipio'),
        ),
        migrations.AlterField(
            model_name='gastoadicional',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.actividad'),
        ),
    ]
