# Generated by Django 3.2.6 on 2022-11-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20221128_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastoadicional',
            old_name='minicipio',
            new_name='municipio',
        ),
    ]
