# Generated by Django 4.1.4 on 2022-12-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_municipio_gastoadicional_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_beneficiario', models.CharField(max_length=50)),
                ('tipo_id_beneficiario', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='solicitudrecurso',
            name='solicitud_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_relacionada', to='home.solicitudrecurso'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.beneficiario'),
        ),
    ]
